### ISSUE TITLE
[PE] Update user guide and developer guide to match our actual implementation

### ISSUE THREAD

**Issue by Meowzz95** [CS2113-AY1819S1-T13-2/main#87]
As per [here](https://nuscs2113-ay1819s1.github.io/website/admin/project-deliverables.html#deliverable-practical-exam)

If our app's behaviour differs from what is written in the guides, it is considered as a bug even if it works as we expected. So please make sure all reachable functions are usable, bug-free and match the description in the guides.

Thanks.
@xllx1 @HansKoh @E0191729

**Comment by HansKoh** [comment]
noted👌
